---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/5013/workspace/2023MavenWebPipeAnsible/target/2023MavenWebPipeAnsible.war"
        dest: "/opt/tomcat/webapps/2023MavenWebPipeAnsible.war"
        remote_src: no

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh
        /opt/tomcat/bin/startup.sh playbook.yml
